# Generated by Django 4.0.4 on 2022-10-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankak', '0003_alter_bankakinput_input_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankakinput',
            name='state',
            field=models.CharField(choices=[('Outside Sudan', 'خارج السودان'), ('Khartoum', 'الخرطوم'), ('Omdurman', 'امدرمان'), ('Bahri', 'بحري'), ('North Kordofan', 'شمال كردفان'), ('Northern', 'الشمالية'), ('Kassala', 'كسّلا'), ('Blue Nile', 'النيل الأزرق'), ('North Darfur', 'شمال دارفور'), ('South Darfur', 'جنوب دارفور'), ('South Kordofan', 'جنوب كردفان'), ('Al Jazirah', 'الجزيرة'), ('White Nile', 'النيل الأبيض'), ('River Nile', 'نهر النيل'), ('Red Sea', 'البحر الأحمر'), ('Al Qadarif', 'القضارف'), ('Sennar', 'سنّار'), ('West Darfur', 'غرب دارفور'), ('Central Darfur', 'وسط دارفور'), ('East Darfur', 'شرق دارفور'), ('East Darfur', 'غرب كردفان')], default='Khartoum', max_length=25),
        ),
    ]
