# Generated by Django 4.0.4 on 2022-10-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankak', '0004_bankakinput_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankakstatus',
            name='current_status',
            field=models.BooleanField(choices=[(True, 'شغال'), (False, 'ما شغال')], default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankakinput',
            name='input_status',
            field=models.BooleanField(choices=[(True, 'شغال'), (False, 'ما شغال')]),
        ),
    ]
