# Generated by Django 4.0.4 on 2023-02-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='framework',
            field=models.CharField(choices=[('django', 'Django'), ('rails', 'Ruby on Rails'), ('express', 'Express'), ('spring', 'Spring'), ('flask', 'Flask')], default='Django', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('csharp', 'C#'), ('ruby', 'Ruby')], default='Python', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='whatsapp_number',
            field=models.CharField(default=249, max_length=12),
            preserve_default=False,
        ),
    ]
