# Generated by Django 4.0.4 on 2022-12-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_arabic',
            field=models.CharField(default='الذماء ', max_length=250),
            preserve_default=False,
        ),
    ]
