# Generated by Django 4.0.4 on 2022-05-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_alter_codesudanquote_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='started_at',
            new_name='starting_at',
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
