# Generated by Django 4.0.4 on 2022-07-13 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_rename_started_at_batch_starting_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='basic_edition_price',
            field=models.IntegerField(default=1200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='curriculum',
            field=models.TextField(default='wlceom; hello; nice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='ending_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='golden_edition_price',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='mode',
            field=models.CharField(choices=[('online', 'أونلاين'), ('offline', 'اوفلاين')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.SmallIntegerField(),
        ),
    ]
