# Generated by Django 4.0.4 on 2022-07-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_alter_batch_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.program'),
        ),
    ]
