# Generated by Django 4.0.4 on 2022-07-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_alter_batch_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='summery',
            field=models.TextField(default='THis program'),
            preserve_default=False,
        ),
    ]
