# Generated by Django 4.0.4 on 2022-07-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_batch_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
