# Generated by Django 4.0.4 on 2022-07-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_alter_batch_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registration.batch'),
        ),
    ]
