# Generated by Django 4.0.4 on 2022-08-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_remove_batch_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_phoned',
            field=models.BooleanField(default=False),
        ),
    ]
