# Generated by Django 4.0.4 on 2022-08-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_registration_is_phoned'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_texted',
            field=models.BooleanField(default=False),
        ),
    ]
