# Generated by Django 4.0.4 on 2022-08-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_alter_registration_is_enroll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
    ]
