# Generated by Django 4.0.4 on 2022-08-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_alter_registration_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='summery',
        ),
        migrations.AddField(
            model_name='batch',
            name='duration_in_weeks',
            field=models.SmallIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='instructor',
            field=models.CharField(default='Ahmed', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='session_duration_in_hours',
            field=models.FloatField(default=1.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='sessions_per_week',
            field=models.SmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='curriculum',
            field=models.TextField(default='Start'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='summery',
            field=models.TextField(default='one'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='in_discord',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_certificated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_graduated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
