# Generated by Django 4.0.4 on 2022-10-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_remove_batch_basic_edition_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='in_discord',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_certificated',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_graduated',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_phoned',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='why_not_enrolled',
        ),
        migrations.AddField(
            model_name='registration',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
