# Generated by Django 4.0.4 on 2022-10-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0035_remove_registration_in_discord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='price',
        ),
    ]
