# Generated by Django 4.0.4 on 2022-10-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0035_remove_batch_basic_edition_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='basic_edition_details',
        ),
        migrations.RemoveField(
            model_name='program',
            name='golden_edition_details',
        ),
    ]
