# Generated by Django 4.0.4 on 2022-10-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_remove_registration_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
