# Generated by Django 4.0.4 on 2022-10-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0037_registration_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(choices=[('University of Khartoum', 'جامعة الخرطوم'), ('Sudan University of Science and Technology', 'جامعة السودان للعلوم و التكنلوجيا'), ('Omdurman Islamic University', 'جامعة أمدرمان الإسلامية'), ('Al Neelain University', 'جامعة النيلين'), ('National Ribat University', 'جامعة الرباط الوطني'), ('Aljazeera University', 'جامعة الجزيرة'), ('Ahfad University for Women', 'جامعة الأحفاد للبنات'), ('Alzaiem Alazhari University', 'جامعة الزعيم الأزهري'), ('Karary University', 'جامعة كرري'), ('University of Science and Technology', 'جامعة العلوم و التقانة'), ('The Future university', 'جامعة المستقبل'), ('University of Medical Sciences and Technology', 'جامعة العلوم الطبية والتكنولوجيا'), ('Sudan international University', 'جامعة السودان المفتوحة'), ('Other', 'أخرى')], default='Other', max_length=64),
        ),
    ]
