# Generated by Django 4.0.4 on 2022-10-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0041_alter_registration_reach_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name_arabic',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='program',
            name='name_english',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reach_channels',
            field=models.CharField(blank=True, choices=[('Our Facebook Page', 'صفحتنا على الفيسبوك'), ('Our Instagram Page', 'صفحتنا على إنستغرام'), ('WhatsApp Group', 'قروب وآتس-أب'), ('Other Social Media', 'شبكات تواصل إجتماعي أخرى'), ('Email', 'البريد الإلكتروني'), ('Friend', 'توصية صديق/ة'), ('Intelligent Pattern Page', 'صفحة Intelligent Pattern'), ('Other', 'أخرى')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='name_arabic',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='track',
            name='name_english',
            field=models.CharField(max_length=128),
        ),
    ]
