# Generated by Django 4.0.4 on 2022-12-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0042_alter_program_name_arabic_alter_program_name_english_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-program', '-id']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-track', '-name_english']},
        ),
    ]
