# Generated by Django 4.0.4 on 2023-01-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0042_alter_program_name_arabic_alter_program_name_english_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-program', '-id']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-track', '-name_english']},
        ),
        migrations.AddField(
            model_name='batch',
            name='whatsapp_url',
            field=models.URLField(default='https://chat.whatsapp.com/GBQIanGNhM0HVIs5w9k8CX'),
            preserve_default=False,
        ),
    ]
