# Generated by Django 4.0.4 on 2023-01-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0043_alter_batch_options_alter_program_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='reach_channels',
            field=models.CharField(blank=True, choices=[('Our Facebook Page', 'صفحتنا على الفيسبوك'), ('Our Instagram Page', 'صفحتنا على إنستغرام'), ('WhatsApp Group', 'قروب وآتس-أب'), ('Other Social Media', 'شبكات تواصل إجتماعي أخرى'), ('Email', 'البريد الإلكتروني'), ('Friend', 'توصية صديق/ة'), ('Intelligent Pattern Page', 'صفحة Intelligent Pattern'), ('Other', 'أخرى'), ('Unknown', 'غير معروف')], max_length=64, null=True),
        ),
    ]
