# Generated by Django 4.0.4 on 2023-02-03 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0044_alter_registration_reach_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
