# Generated by Django 4.0.4 on 2023-01-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_arabic', models.CharField(max_length=64)),
                ('name_english', models.CharField(max_length=64)),
                ('rank', models.SmallIntegerField()),
                ('facebook_url', models.URLField()),
                ('linkedin_url', models.URLField()),
            ],
        ),
    ]
