# Generated by Django 4.0.4 on 2023-01-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='github_url',
            field=models.URLField(default='https://github.com/aelsir/'),
            preserve_default=False,
        ),
    ]
