# Generated by Django 4.0.4 on 2023-01-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_developer_github_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'permissions': [('contributor', 'add or remove in developer ranking')]},
        ),
    ]
