# Generated by Django 4.0.4 on 2023-01-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_alter_developer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='country',
            field=models.CharField(choices=[('sd', 'السودان')], default='sd', max_length=2),
        ),
    ]
