# Generated by Django 4.0.4 on 2023-01-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_developer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='followers',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
