# Generated by Django 4.0.4 on 2023-01-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_developer_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
