# Generated by Django 4.0.4 on 2023-01-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_developer_twitter_url_alter_developer_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='contribs',
            field=models.IntegerField(blank=True, default=10000),
            preserve_default=False,
        ),
    ]
