# Generated by Django 4.0.4 on 2023-01-31 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0008_alter_developer_contribs_alter_developer_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='rank',
        ),
    ]
